cameras:
  fence10:
    line:
    - - 474
      - 148
    - - 592
      - 127
    - - 676
      - 131
    - - 795
      - 130
    - - 1001
      - 134
    - - 1250
      - 156
    - - 1573
      - 220
    - - 1899
      - 293
    regions:
      region1:
      - - 1878
        - 379
      - - 1608
        - 302
      - - 1552
        - 292
      - - 1297
        - 235
      - - 1232
        - 226
      - - 1044
        - 198
      - - 982
        - 188
      - - 832
        - 177
      - - 785
        - 179
      - - 694
        - 168
      - - 655
        - 170
      - - 594
        - 169
      - - 589
        - 137
      - - 654
        - 135
      - - 697
        - 135
      - - 780
        - 136
      - - 852
        - 137
      - - 972
        - 134
      - - 1038
        - 139
      - - 1231
        - 158
      - - 1293
        - 165
      - - 1551
        - 218
      - - 1606
        - 234
      - - 1885
        - 303
      region2:
      - - 258
        - 283
      - - 296
        - 211
      - - 414
        - 209
      - - 614
        - 221
      - - 825
        - 231
      - - 1163
        - 275
      - - 1433
        - 335
      - - 1744
        - 399
      - - 1899
        - 453
      - - 1899
        - 631
      - - 1893
        - 818
      - - 1196
        - 630
    resolution:
      height: 1080
      width: 1920
    rtsp_url: rtsp://admin:Hanet123@10.128.55.223:554/media/live/105
    updated_at: '2026-05-09T07:42:06.898385'
  fence7:
    line: []
    regions:
      region1: []
      region2:
      - - 933
        - 113
      - - 951
        - 104
      - - 1066
        - 171
      - - 1149
        - 229
      - - 1191
        - 253
      - - 1256
        - 310
      - - 1338
        - 373
      - - 1427
        - 451
      - - 1478
        - 484
      - - 1545
        - 558
      - - 1618
        - 627
      - - 1662
        - 672
      - - 1703
        - 712
      - - 1773
        - 778
      - - 1854
        - 859
      - - 1892
        - 920
      - - 1877
        - 972
      - - 1854
        - 994
      - - 1710
        - 812
      - - 1487
        - 603
      - - 1312
        - 443
      - - 1160
        - 293
      - - 1018
        - 183
    resolution:
      height: 1080
      width: 1920
    rtsp_url: rtsp://admin:Hanet123@10.128.55.202:554/media/live/105
    updated_at: '2026-05-13T08:52:59.561209'
  fence8:
    line:
    - - 482
      - 222
    - - 614
      - 206
    - - 744
      - 209
    - - 874
      - 194
    - - 1098
      - 191
    - - 1437
      - 241
    - - 1785
      - 304
    - - 1915
      - 348
    regions:
      region1:
      - - 481
        - 230
      - - 551
        - 220
      - - 614
        - 213
      - - 736
        - 215
      - - 881
        - 201
      - - 1105
        - 201
      - - 1437
        - 246
      - - 1788
        - 312
      - - 1914
        - 359
      - - 1910
        - 427
      - - 1434
        - 316
      - - 1119
        - 265
      - - 741
        - 243
      - - 493
        - 249
      region2:
      - - 276
        - 343
      - - 325
        - 280
      - - 545
        - 275
      - - 782
        - 300
      - - 1028
        - 340
      - - 1212
        - 373
      - - 1512
        - 437
      - - 1786
        - 491
      - - 1903
        - 531
      - - 1914
        - 788
      - - 693
        - 466
    resolution:
      height: 1080
      width: 1920
    rtsp_url: rtsp://admin:Hanet123@10.128.55.225:554/media/live/105
    updated_at: '2026-05-09T07:52:30.247521'
  fence9:
    line:
    - - 437
      - 130
    - - 563
      - 130
    - - 783
      - 171
    - - 1001
      - 211
    - - 1313
      - 286
    - - 1685
      - 400
    - - 1918
      - 494
    regions:
      region1:
      - - 437
        - 146
      - - 607
        - 172
      - - 776
        - 205
      - - 1012
        - 242
      - - 1300
        - 311
      - - 1680
        - 422
      - - 1918
        - 512
      - - 1915
        - 605
      - - 1302
        - 387
      - - 773
        - 252
      - - 444
        - 180
      region2:
      - - 59
        - 180
      - - 88
        - 135
      - - 583
        - 221
      - - 751
        - 279
      - - 978
        - 333
      - - 1309
        - 412
      - - 1637
        - 523
      - - 1860
        - 615
      - - 1914
        - 715
      - - 1903
        - 834
    resolution:
      height: 1080
      width: 1920
    rtsp_url: rtsp://admin:Hanet123@10.128.55.222:554/media/live/105
    updated_at: '2026-05-10T11:27:39.736101'
ptz_presets:
  '1':
    line:
    - - 136
      - 78
    - - 636
      - 183
    - - 634
      - 196
    - - 132
      - 91
    preset_id: 1
    preset_name: fence8
    resolution:
      height: 360
      width: 640
    updated_at: '2026-05-06T01:22:07.032201'
  '2':
    line:
    - - 9
      - 223
    - - 531
      - 95
    - - 533
      - 111
    - - 11
      - 243
    preset_id: 2
    preset_name: fence9
    resolution:
      height: 360
      width: 640
    updated_at: '2026-05-06T01:13:08.212865'
