export const INFORMATION_COLOR = "#0A84FF";
export const ALERT_COLOR = "#DF3A4D";
export const WARNING_COLOR = "#FECF4D";
export const NORMAL_COLOR = "#000000";

export const EVENT_TYPES = [
    {
        key: "EMPLOYEE",
        types: [0],
        label: "Nhân viên",
        color: INFORMATION_COLOR,
        aliasName: "Nhân viên",
    },
    {
        key: "CUSTOMER",
        types: [1],
        label: "Khách hàng",
        color: WARNING_COLOR,
        aliasName: "Khách hàng",
    },
    {
        key: "STRANGER",
        types: [2, 4, 5],
        label: "Người lạ",
        color: ALERT_COLOR,
        aliasName: "Người lạ",
    },
    {
        key: "ALARM",
        types: [3],
        label: "Báo động",
        color: ALERT_COLOR,
        aliasName: "Báo động",
    },
    {
        key: "CHECK_UNIFORM",
        types: [8],
        label: "Kiểm tra trang phục",
        color: NORMAL_COLOR,
        aliasName: "Kiểm tra trang phục",
    },
    {
        key: "LICENSE_PLATES",
        types: [11],
        label: "Biển số xe",
        color: NORMAL_COLOR,
        aliasName: "Biển số xe",
    },
    {
        key: "MOTOBIKE",
        types: [13, 30],
        label: "Xe",
        color: INFORMATION_COLOR,
        aliasName: "Xe",
    },
    {
        key: "CAR",
        types: [12],
        label: "Ô tô",
        color: NORMAL_COLOR,
        aliasName: "Xe oto",
    },
    {
        key: "QACODE",
        types: [7],
        label: "QA Code",
        color: INFORMATION_COLOR,
    },
    {
        key: "FIRE",
        types: [28],
        label: "Lửa",
        color: ALERT_COLOR,
        aliasName: "Lửa",
    },
    {
        key: "WATCH_PHONE",
        types: [41],
        label: "Xem điện thoại",
        color: ALERT_COLOR,
        aliasName: "Xem điện thoại",
    },
    {
        key: "HOLD_WEAPON",
        types: [43],
        label: "Cầm vũ khí",
        color: ALERT_COLOR,
        aliasName: "Cầm vũ khí",
    },
    {
        key: "SMOKING",
        types: [44],
        label: "Hút thuốc",
        color: ALERT_COLOR,
        aliasName: "Hút thuốc",
    },
    {
        key: "EXPOSE_GARBAGE",
        types: [46],
        label: "Xả rác",
        color: ALERT_COLOR,
        aliasName: "Xả rác",
    },
    {
        key: "INTRUSION",
        types: [47],
        label: "Xâm nhập",
        color: ALERT_COLOR,
        aliasName: "Xâm nhập",
    },
    {
        key: "CALL",
        types: [48],
        label: "Gọi điện thoại",
        color: ALERT_COLOR,
        aliasName: "Gọi điện thoại",
    },
    {
        key: "FLIGHT",
        types: [49],
        label: "Đánh nhau",
        color: ALERT_COLOR,
        aliasName: "Đánh nhau",
    },
    {
        key: "STAND",
        types: [52],
        label: "Đứng dậy",
        color: ALERT_COLOR,
        aliasName: "Đứng dậy",
    },
    {
        key: "EXIT",
        types: [53],
        label: "Rời đi",
        color: ALERT_COLOR,
        aliasName: "Rời đi",
    },
    {
        key: "OVER_WALL",
        types: [54],
        label: "Trèo tường",
        color: ALERT_COLOR,
        aliasName: "Trèo tường",
    },
    {
        key: "LEAVE_POSITION",
        types: [55],
        label: "Rời bỏ vị trí",
        color: ALERT_COLOR,
        aliasName: "Rời bỏ vị trí",
    },
    {
        key: "GATHER",
        types: [56],
        label: "Tụ tập đám đông",
        color: ALERT_COLOR,
        aliasName: "Tụ tập đám đông",
    },
    {
        key: "ENVELOPE",
        types: [57],
        label: "Phong bì",
        color: ALERT_COLOR,
        aliasName: "Phong bì",
    },
    {
        key: "CCCD",
        types: [58],
        label: "Căn Cước Công Dân",
        color: NORMAL_COLOR,
        aliasName: "Căn Cước Công Dân",
    },
    {
        key: "DRIVE_WRONG_WAY",
        types: [60],
        label: "Lái xe ngược chiều",
        color: NORMAL_COLOR,
        aliasName: "Lái xe ngược chiều",
    },
    {
        key: "CHECKPOINT",
        types: [61],
        label: "Điểm kiểm tra",
        color: NORMAL_COLOR,
        aliasName: "Điểm kiểm tra",
    },
    {
        key: "ABNORMAL",
        types: [70],
        label: "Bất thường",
        color: ALERT_COLOR,
        aliasName: "Bất thường",
    },
    {
        key: "ABNORMAL_ROPE",
        types: [71],
        label: "Cầm dây",
        color: ALERT_COLOR,
        aliasName: "Cầm dây",
    },
    {
        key: "ABNORMAL_STANDING",
        types: [72],
        label: "Di chuyển",
        color: ALERT_COLOR,
        aliasName: "Di chuyển",
    },
    {
        key: "ABNORMAL_QUANTITY",
        types: [73],
        label: "Thiếu người",
        color: ALERT_COLOR,
        aliasName: "Thiếu người",
    },
    {
        key: "STRANGER_AREA",
        types: [74],
        label: "Người lạ trong khu vực",
        color: ALERT_COLOR,
        aliasName: "Người lạ trong khu vực",
    },
    {
        key: "BUFFER_AREA_ACCESS",
        types: [75],
        label: "Vào khu vực cấm",
        color: ALERT_COLOR,
        aliasName: "Vào khu vực cấm",
    },
    {
        key: "CAMERA_COVER",
        types: [76],
        label: "Che camera",
        color: ALERT_COLOR,
        aliasName: "Che camera",
    },
     {
                key: "MASK",
                types: [77],
                label: "Đeo khẩu trang",
                color: ALERT_COLOR,
                aliasName: "Đeo khẩu trang",
            },
          {
                key: "HAT",
                types: [78],
                label: "Đội mũ",
                color: ALERT_COLOR,
                aliasName: "Đội mũ",
            },
    {
        key: "BAG",
        types: [79],
        label: "Đem các loại túi vào khu vực kiểm đếm",
        color: ALERT_COLOR,
        aliasName: "Đem các loại túi vào khu vực kiểm đếm",
    },
    {
        key: "ALONE",
        types: [80],
        label: "Vào không gian đệm hoặc kho tiền quá 1 phút",
        color: ALERT_COLOR,
        aliasName: "Vào không gian đệm hoặc kho tiền quá 1 phút",
    },
    {
        key: "WRONG_COUNTING_PROCESS",
        types: [81],
        label: "Đếm tiền không theo quy trình",
        color: ALERT_COLOR,
        aliasName: "Đếm tiền không theo quy trình",
    },
    {
        key: "OVER_TIME_DOOR_OPENING",
        types: [82],
        label: "Mở cửa kho tiền quá thời gian quy định",
        color: ALERT_COLOR,
        aliasName: "Mở cửa kho tiền quá thời gian quy định",
    },
    {
        key: "WRONG_UNIFORM",
        types: [83],
        label: "Trang phụ sai khi vào kho tiền",
        color: ALERT_COLOR,
        aliasName: "Trang phụ sai khi vào kho tiền",
    }, 
    {
        key: "SUICIDE",
        types: [84],
        label: "Treo cổ tự tử",
        color: ALERT_COLOR,
        aliasName: "Treo cổ tự tử",
    },
     {
        key: "LOITERING",
        types: [85],
        label: "Lảng vảng hành lang",
        color: ALERT_COLOR,
        aliasName: "Lảng vảng hành lang",
    },
   
];

export const ALERT_EVENT_TYPES = [
    "ALARM",
];

export const EMAP_ALERT_EVENT_TYPES = [
    "FIRE", 
     "ABNORMAL_QUANTITY",
    "FLIGHT",
    "ALARM",
    "ABNORMAL",
    "OVER_WALL",
    "ABNORMAL_ROPE",
    "ABNORMAL_STANDING",
    "BUFFER_AREA_ACCESS",
    "SUICIDE",
    "LOITERING",
    "CAMERA_COVER",
    "GATHER",
    "INTRUSION",
];

export const EMAP_ALERT_EVENT_AUDIO = {
    FIRE: "/audio/Tieng-coi-canh-bao.mp3",
    ABNORMAL_QUANTITY: "/audio/Tieng-coi-canh-bao.mp3",
    FLIGHT: "/audio/Tieng-coi-canh-bao.mp3",
    ALARM: "/audio/Tieng-coi-canh-bao.mp3",
    ABNORMAL: "/audio/Tieng-coi-canh-bao.mp3",
    OVER_WALL: "/audio/Tieng-coi-canh-bao.mp3",
    ABNORMAL_ROPE: "/audio/Tieng-coi-canh-bao.mp3",
    ABNORMAL_STANDING: "/audio/Tieng-coi-canh-bao.mp3",
    BUFFER_AREA_ACCESS: "/audio/Tieng-coi-canh-bao.mp3",
    SUICIDE: "/audio/Tieng-coi-canh-bao.mp3",
    LOITERING: "/audio/Tieng-coi-canh-bao.mp3",
    CAMERA_COVER: "/audio/Tieng-coi-canh-bao.mp3",
    GATHER: "/audio/Tieng-coi-canh-bao.mp3",
    INTRUSION: "/audio/Tieng-coi-canh-bao.mp3",
};

export const ALERT_EVENT_AUDIO = {
    FIRE: "/audio/alert.mp3",
    WATCH_PHONE: "/audio/alert.mp3",
    HOLD_WEAPON: "/audio/alert.mp3",
    SMOKING: "/audio/alert.mp3",
    EXPOSE_GARBAGE: "/audio/alert.mp3",
    INTRUSION: "/audio/alert.mp3",
    FLIGHT: "/audio/alert.mp3",
    STAND: "/audio/alert.mp3",
    EXIT: "/audio/alert.mp3",
    CALL: "/audio/alert.mp3",
    OVER_WALL: "/audio/alert.mp3",
};
